version: "3.9"

services:

  mysql:

    image: mysql:8.4

    container_name: mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: n3u3da!
      MYSQL_DATABASE: friends_community

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pn3u3da!"]
      interval: 10s
      timeout: 5s
      retries: 10

  springboot:

    build: .

    container_name: friends-app

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_URL: jdbc:mysql://mysql:3306/friends_community
      DB_USERNAME: root
      DB_PASSWORD: n3u3da!

    ports:
      - "8080:8080"

volumes:

  mysql_data: