name: My First GitHub Action

on:
  push:
    branches:
      - master

jobs:
  say-hello:

    runs-on: ubuntu-latest

    steps:

      - name: Print Hello

        run: echo "Hello from GitHub Actions! OBB!!!!"